'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXWebApplication1

    Public Partial Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' Gantt control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Gantt As Global.DevExpress.Web.ASPxGantt.ASPxGantt

        ''' <summary>
        ''' TasksDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TasksDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' DependenciesDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DependenciesDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' ResourcesDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ResourcesDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' ResourceAssignmentsDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ResourceAssignmentsDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
